Update patch set 1
Patch Set 1:

Technical help is needed...! please

If features/features4-snmp4sdn/pom.xml, try with the whole block (lines 45-59) removed, then build fail as below:

2017-04-21 19:43:09,277 | ERROR | ime-limited test | SingleFeatureTest                | 73 - PAXEXAM-PROBE-62e508f6-ca55-4e2a-8a4c-28fadf1226e2 - 0.0.0 | installFeature() failed
org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=odl-snmp4sdn-snmp4sdn; type=karaf.feature; version="[0.5.0.SNAPSHOT,0.5.0.SNAPSHOT]"; filter:="(&(osgi.identity=odl-snmp4sdn-snmp4sdn)(type=karaf.feature)(version>=0.5.0.SNAPSHOT)(version<=0.5.0.SNAPSHOT))" [caused by: Unable to resolve odl-snmp4sdn-snmp4sdn/0.5.0.SNAPSHOT: missing requirement [odl-snmp4sdn-snmp4sdn/0.5.0.SNAPSHOT] osgi.identity; osgi.identity=org.opendaylight.snmp4sdn.plugin-shell; type=osgi.bundle; version="[0.5.0.SNAPSHOT,0.5.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.opendaylight.snmp4sdn.plugin-shell/0.5.0.SNAPSHOT: missing requirement [org.opendaylight.snmp4sdn.plugin-shell/0.5.0.SNAPSHOT] osgi.service; effective:=active; filter:="(objectClass=org.opendaylight.snmp4sdn.ICore)"]]

The artifacts mentioned above, (1)odl-snmp4sdn-snmp4sdn and (2)org.opendaylight.snmp4sdn.plugin-shell. Their relationship is, (2) is a Karaf CLI bundle and it invokes (1) by the interface org.opendaylight.snmp4sdn.ICore that (1) exposes. In (1)'s pom (snmp4sdnsnmp4sdn/pom.xml), in <Export-Package> we have exposed org.opendaylight.snmp4sdn.

Patch-set: 1