Update patch set 1
Patch Set 1:

There's a failure when testing after build, as follows
========================================

root@ubuntu:~/snmp4sdn_test/features$ mvn clean install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.opendaylight.snmp4sdn:features-snmp4sdn:jar:0.1.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-resources-plugin is missing. @ line 80, column 18
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 93, column 18
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building features-snmp4sdn 0.1.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.3:clean (default-clean) @ features-snmp4sdn ---
[INFO] Deleting file set: /home/root/snmp4sdn_test/features/target (included: [**], excluded: [])
[INFO] 
[INFO] --- properties-maven-plugin:1.0-alpha-2:set-system-properties (default) @ features-snmp4sdn ---
[INFO] Set 1 system property
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (filter) @ features-snmp4sdn ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ features-snmp4sdn ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ features-snmp4sdn ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ features-snmp4sdn ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/root/snmp4sdn_test/features/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ features-snmp4sdn ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ features-snmp4sdn ---
[INFO] Surefire report directory: /home/root/snmp4sdn_test/features/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.opendaylight.yangtools.featuretest.SingleFeatureTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/root/.m2/repository/org/slf4j/slf4j-jdk14/1.7.5/slf4j-jdk14-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/root/.m2/repository/org/apache/karaf/org.apache.karaf.client/3.0.1/org.apache.karaf.client-3.0.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/root/.m2/repository/org/ops4j/pax/logging/pax-logging-api/1.7.2/pax-logging-api-1.7.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/root/.m2/repository/ch/qos/logback/logback-classic/1.0.9/logback-classic-1.0.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
?? 03, 2014 10:49:26 ?? org.opendaylight.yangtools.featuretest.PerRepoTestRunner <init>
??: Creating test runners for repoURL file:/home/root/snmp4sdn_test/features/target/classes/features.xml recursive false
?? 03, 2014 10:49:26 ?? org.ops4j.pax.exam.junit.PaxExam <init>
??: creating PaxExam runner for class org.opendaylight.yangtools.featuretest.SingleFeatureTest
?? 03, 2014 10:49:26 ?? org.ops4j.pax.exam.spi.DefaultExamSystem create
??: Pax Exam System (Version: 3.5.0) created.
?? 03, 2014 10:49:26 ?? org.ops4j.pax.exam.spi.PaxExamRuntime sanityCheck
SEVERE: Ambiguous TestContainer:  org.ops4j.pax.exam.karaf.container.internal.KarafTestContainerFactory
?? 03, 2014 10:49:26 ?? org.ops4j.pax.exam.spi.PaxExamRuntime sanityCheck
SEVERE: Ambiguous TestContainer:  org.ops4j.pax.exam.nat.internal.NativeTestContainerFactory
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.475 sec <<< FAILURE! - in org.opendaylight.yangtools.featuretest.SingleFeatureTest
initializationError(org.opendaylight.yangtools.featuretest.SingleFeatureTest)  Time elapsed: 0.005 sec  <<< ERROR!
org.ops4j.pax.exam.TestContainerException: Too many TestContainer implementations in Classpath
	at org.ops4j.pax.exam.spi.PaxExamRuntime.sanityCheck(PaxExamRuntime.java:181)
	at org.ops4j.pax.exam.spi.PaxExamRuntime.getTestContainerFactory(PaxExamRuntime.java:69)
	at org.ops4j.pax.exam.spi.reactors.ReactorManager.createsTestContainerFactory(ReactorManager.java:338)
	at org.ops4j.pax.exam.spi.reactors.ReactorManager.createReactor(ReactorManager.java:311)
	at org.ops4j.pax.exam.spi.reactors.ReactorManager.prepareReactor(ReactorManager.java:186)
	at org.ops4j.pax.exam.junit.PaxExam.<init>(PaxExam.java:92)
	at org.opendaylight.yangtools.featuretest.PerFeatureRunner.<init>(PerFeatureRunner.java:46)
	at org.opendaylight.yangtools.featuretest.PerRepoTestRunner.runnersFromFeatures(PerRepoTestRunner.java:83)
	at org.opendaylight.yangtools.featuretest.PerRepoTestRunner.runnersFromRepoURL(PerRepoTestRunner.java:63)
	at org.opendaylight.yangtools.featuretest.PerRepoTestRunner.runnersFromRepoURL(PerRepoTestRunner.java:56)
	at org.opendaylight.yangtools.featuretest.PerRepoTestRunner.<init>(PerRepoTestRunner.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Results :

Tests in error: 
  SingleFeatureTest.initializationError » TestContainer Too many TestContainer i...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.723s
[INFO] Finished at: Wed Sep 03 22:49:26 CST 2014
[INFO] Final Memory: 19M/47M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project features-snmp4sdn: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/root/snmp4sdn_test/features/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Patch-set: 1